"""empty message

Revision ID: ff18cb60c181
Revises: baa1c22d38fd
Create Date: 2025-09-02 09:09:28.142761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff18cb60c181'
down_revision = 'baa1c22d38fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('working', sa.String(length=50), nullable=False),
    sa.Column('break', sa.String(length=50), nullable=False),
    sa.Column('holiday', sa.String(length=50), nullable=False),
    sa.Column('not_working', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('remaining_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('payroll', sa.String(length=100), nullable=False),
    sa.Column('contract', sa.String(length=100), nullable=False),
    sa.Column('supporting_documents', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('holidays', sa.String(length=100), nullable=False),
    sa.Column('shift_change', sa.String(length=100), nullable=False),
    sa.Column('schedule_change', sa.String(length=100), nullable=False),
    sa.Column('salary_advance', sa.String(length=100), nullable=False),
    sa.Column('others', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('DNI', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['DNI'])
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status_id')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('rol')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('DNI')
        batch_op.drop_column('first_name')
        batch_op.drop_column('surname')
        batch_op.drop_column('last_name')

    op.drop_table('signing')
    op.drop_table('request_type')
    op.drop_table('document_type')
    op.drop_table('schedule')
    op.drop_table('request')
    op.drop_table('holidays')
    op.drop_table('document')
    op.drop_table('status')
    # ### end Alembic commands ###
